version: '3.8'

services:
  # Docker-in-Docker service - allows Jenkins to build Docker images
  dind:
    image: docker:dind
    container_name: dind
    privileged: true  
    restart: unless-stopped
    networks:
      jenkins:
        aliases:
          - docker 
    environment:
      # Enable TLS for secure communication between Jenkins and Docker
      DOCKER_TLS_CERTDIR: /certs
    volumes:

      # Storing TLS certs
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client

      # Data persistence for Jenkins
      - jenkins-data:/var/jenkins_home
      - docker-data:/var/lib/docker  # Caching for faster builds
    ports:
      - "2376:2376" # Daemon port with TLS

  # Jenkins service - CI/CD automation server
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    restart: unless-stopped
    user: root  # Run with root perms
    networks:
      - jenkins
    environment:
      # Configuring Jenkins for DinD service
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1

    volumes:
      # Mounting docker client certs
      - docker-certs-client:/certs/client:ro
      - jenkins-data:/var/jenkins_home
    ports:
      - "8080:8080" # Jenkins UI
      - "50000:50000" # Jenkins agent 
    depends_on:
      - dind

# Define named volumes for data persistence
volumes:
  docker-certs-ca:
    driver: local
  docker-certs-client:
    driver: local
  jenkins-data:
    driver: local
  docker-data:
    driver: local

# Network for Jenkins services
networks:
  jenkins:
    driver: bridge
